# Claves básicas de tu proyecto (Cámbialas por las tuyas de SonarQube)
sonar.projectKey=SafeGuard_Ops
sonar.projectName=SafeGuard Ops

# 1. Definir dónde está el código fuente (Ambas carpetas)
sonar.sources=SafeGuard_Back/src, SafeGuard_Front/src

# 2. Definir dónde están los tests (Para que no los cuente como código a evaluar)
sonar.tests=SafeGuard_Back/src/__tests__, SafeGuard_Front/src/__tests__

# 3. ¡LA CONEXIÓN MÁGICA! Le decimos dónde encontrar el lcov.info de Vite/Vitest
sonar.javascript.lcov.reportPaths=SafeGuard_Back/coverage/lcov.info, SafeGuard_Front/coverage/lcov.info

# 4. Le decimos qué archivos ignorar del análisis de cobertura
# sonar.coverage.exclusions=**/*.test.ts, **/*.test.tsx, **/main.tsx, **/index.ts